name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install cargo-bundle
        if: matrix.os == 'macos-latest'
        run: cargo install cargo-bundle
      - name: Install NSIS
        if: matrix.os == 'windows-latest'
        run: choco install nsis -y
      - name: Build
        run: cargo build --workspace --release
      - name: Package
        run: cargo run --package packaging --bin packager

